### ISSUE TITLE
bug: Dataloss

### ISSUE THREAD

**Issue by vortex73** [acmpesuecc/pasture#1]
After uploading a file to the server, when I view the hashed file, there is evident dataloss. Ensure that the entire contents of the file are being transferred.

**Comment by kavin81** [comment]
can i get assigned @vortex73

**Comment by vortex73** [comment]
!assign @kavin81 50

**Comment by kavin81** [comment]
@vortex73 I hope it works , it was an EOL issue i was using CLRF but nim made a LF file

**Comment by vortex73** [comment]
checking now...
