### ISSUE TITLE
feat: add a data retreival method

### ISSUE THREAD

**Issue by vortex73** [acmpesuecc/pasture#2]
There has beeen a long standing [proposal](https://github.com/acmpesuecc/pasture/blob/d937decc91aa0254239e4e108a9eec0ea67ce786/src/pasture.nim#L3) for a GET method to fetch data from pasture.

- [ ] Must be able to fetch data using `curl localhost:8000/<hash>`

**Comment by kavin81** [comment]
can i get assigned @vortex73

**Comment by vortex73** [comment]
!assign @kavin81 30

**Comment by sherlockhome12** [comment]
hey can I get assigned this??

**Comment by kavin81** [comment]
@vortex73  approve #8

**Comment by vortex73** [comment]
!assign @kavin81 30

**Comment by vortex73** [comment]
@kavin81 please clean your code and commit only files needed for this commit. And then make a PR mentioning this issue.

**Comment by mebinthattil** [comment]
Can this issue be assigned to me please
