### ISSUE TITLE
feat: CLI Overhaul

### ISSUE THREAD

**Issue by vortex73** [acmpesuecc/pasture#4]
As you may have noticed, the pasture CLI looks quite barebones and wouldn't hurt from a design overhaul.

- [ ] Add Salient Error Messages and Logging
- [ ] Make use of [ANSI Escape Sequences](https://www.lihaoyi.com/post/BuildyourownCommandLinewithANSIescapecodes.html) to unlock terminal colors

**Comment by kavin81** [comment]
@vortex73  can i be assigned to this

**Comment by vortex73** [comment]
!assign @kavin81 50

**Comment by kavin81** [comment]
@vortex73  #10
